.TH "dsh" 1 "2002 Oct 22" "Debian-Beowulf/Dancer" "Dancer ツールリファレンス"
\" 元ファイルのバージョン
\" original-version: 1.9
.SH 名前
dsh \- 分散シェル．もしくはダンサーのシェル
.SH 書式
.BI "dsh [-m " "マシン名" " | -a | -g " "グループ名" "] [-r " \
"リモートシェル名" "] [-c | -w | -i] -- " "コマンドライン"
.SH 説明
.B dsh
は複数のマシンで同時にコマンドを実行するためのユーティリティーです．
このユーティリティーはBourneシェルで表現すると
.B "for a in $(seq 1 10); do rsh $a command; done"
と同等の事ができます．

.SH オプション
利用可能なオプションは以下の通りです
.TP
.B "--verbose | -v" 
冗長な出力を出します．
.PP
.TP
.B "--quiet | -q"
出力を静かにします．
.PP
.TP
.BI "--machine | -m " "[マシン名[,マシン名]*]"
.I マシン名
をコマンドが実行されるマシンの一覧に追加します．
.I マシン名
の形式は
.I ユーザ名@マシン名
という形をとります．この形式を利用すると
.I ユーザ名
でリモートホストにログインできます．

バージョン 0.21.4 から
.I "ユーザ名@マシン名,ユーザ名@マシン名,ユーザ名@マシン名"
の形式で複数のホストをコンマ区切りで指定することができるようになりました．

.TP
.BI "--all | -a " 
Add all machines found in 
.B /etc/dsh/machines.list
にある全ホストを指定したコマンドを実行するホストの一覧に追加します．

.TP
.BI "--group " "groupname" " | -g " "groupname "
.BI /etc/dsh/group/ グループ名
にある全ホストを指定したコマンドを実行するホストの一覧に追加します．

グループ名が
.BI "@ネットグループ"
の形式で指定されているのなら，指定されたネットグループを
コマンドを実行するためのホストの一覧に追加します．

.TP
.BI "--file " "マシンファイル" " | -f " "マシンファイル"
指定したファイルにある全ホストを指定したコマンドを実行するホストの一覧に追加します．

バージョン 0.21.4 から同じマシンを複数回指定すると，
一つの実行にマージされるようになりました．

.TP
.BI "--remoteshell " "シェル名 " "| -r " "シェル名 "
.I シェル名
というリモートシェルを利用する．
通常 "rsh" や "remsh" や "ssh" が利用可能です．

.TP
.BI "--remoteshellopt " "リモートシェルオプション " "| -o " "リモートシェルオプション "
.I リモートシェルオプション
をリモートシェルに与えるオプションのリストに追加する．

.TP
.BI "--help | -h "
ヘルプメッセージを出力して終了する．

.TP
.BI "--wait-shell | -w " 
各マシンで実行し，実行し終ってから次のマシンで実行する．

.TP
.BI "--concurrent-shell | -c "
シェルを並列に実行する．

.TP
.BI "--show-machine-names | -M "
マシン名を標準出力の出力に追加する．
.B "--concurrent-shell" 
オプションと同時に使うと出力が多少は見やすくなる．

.TP
.BI "--duplicate-input | -i "
dshプロセスの入力を各リモートプロセスに分配する．
.B "--concurrent-shell" 
オプションを指定している必要がある．

.TP
.BI "--bufsize | -b [" "バッファサイズ(バイト)" "]"
.B "--duplicate-input" 
の入力を複製する際に利用するバッファサイズを指定する．

.TP
.BI "--version | -V "
バージョン情報を出力して終了する．

.TP
.BI "--num-topology | -N "
トポロジを１から変更する．
１がデフォルトの１ノードから全ノードにシェルを実行するスタイルです．
2以上の値に指定すると，dshが他のマシンでも実行されるようになります．

.SH "終了コード"
通常はゼロです．並列実行したタスクが返して来たエラーコードをまともに使う方法はあまり無いと考えられています．

コマンドラインオプションの失敗があった場合は，EXIT_FAILUREを返します．

.SH "例"
.TP
.B "dsh -a w "
全ワークステーションにログインしているユーザの一覧を表示します．
.PP
.TP
.B "dsh -r ssh -a -- w "
sshを利用して，全ワークステーションにログインしているユーザの一覧を表示します．
(sshを利用するときには，ssh-agentを利用するのが良いでしょう．)
.PP
.TP
.B "dsh -r ssh -m node1 -m node2 -c -- 'echo $HOSTNAME $(cat/proc/loadavg )'"
node1とnode2の負荷平均を表示します．
.PP
.SH "ファイル"
.TP
.B "@sysconfdir@/machines.list | $(HOME)/.dsh/machines.list"
.B -a
コマンドラインオプションが指定されたときに利用するマシンの一覧．
.PP
.TP
.BI "@sysconfdir@/group/" "groupname" " | $(HOME)/.dsh/group/" "groupname" 
.BI "-g " "グループ名"
オプションが指定されたときに利用するマシンの一覧

.PP
.TP
.B "@sysconfdir@/dsh.conf | $(HOME)/.dsh/dsh.conf "
毎日使うデフォルト設定の書いてあるファイル．
.PP
.SH "バグ"
ファイルをコピーするための
.B "dcp"
プログラムがあるべきだろう．

設定ファイルももっと柔軟になるべきだ．


.SH "著者"
上川純一 (dancer@debian.org)

ホームページは
.B "http://www.netfort.gr.jp/~dancer/software/dsh.html"
にあります．

.SH "関連項目"
.BR "rsh" "(1), " 
.BR "ssh" "(1), "
.BR "remsh" "(1), "
.BR "dsh.conf" "(5) "
